Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = DataFrame(np.arange(15).reshape(5,3))
df.index = ["NewYork", "LosAngeles", "Atlanta", "Boston", "SanFrancisco"]
df.columns = ["January", "February", "March"]
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m df [38;5;241m=[39m [43mDataFrame[49m(np[38;5;241m.[39marange([38;5;241m15[39m)[38;5;241m.[39mreshape([38;5;241m5[39m,[38;5;241m3[39m))
[1;32m      2[0m df[38;5;241m.[39mindex [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mNewYork[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mLosAngeles[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mAtlanta[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mBoston[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mSanFrancisco[39m[38;5;124m"[39m]
[1;32m      3[0m df[38;5;241m.[39mcolumns [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mJanuary[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mFebruary[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mMarch[39m[38;5;124m"[39m]

[0;31mNameError[0m: name 'DataFrame' is not defined
NameError: name 'DataFrame' is not defined

